"""add total to invoice table

Revision ID: 175620a8b8f3
Revises: e5a68fd5cdae
Create Date: 2025-03-02 14:16:30.168949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "175620a8b8f3"
down_revision: Union[str, None] = "e5a68fd5cdae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fabinvoice", sa.Column("total", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fabinvoice", "total")
    # ### end Alembic commands ###
