"""Add Invoice Tables

Revision ID: 20ea2521dc53
Revises: f1c8346dc773
Create Date: 2025-02-18 09:42:12.834458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20ea2521dc53"
down_revision: Union[str, None] = "f1c8346dc773"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fabinvoice",
        sa.Column("invoice_number", sa.Integer(), nullable=False),
        sa.Column("invoice_date", sa.DateTime(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.add_column("faborder", sa.Column("fk_invoice", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "faborder", "fabinvoice", ["fk_invoice"], ["pk"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "faborder", type_="foreignkey")
    op.drop_column("faborder", "fk_invoice")
    op.drop_table("fabinvoice")
    # ### end Alembic commands ###
