"""Add invoice to oder tables

Revision ID: 33082a936b3a
Revises: 132e0bfba9b0
Create Date: 2025-02-07 20:12:19.854620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "33082a936b3a"
down_revision: Union[str, None] = "132e0bfba9b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("faborder", sa.Column("paid", sa.Boolean()))
    op.add_column("faborder", sa.Column("invoice_str", sqlmodel.sql.sqltypes.AutoString()))
    op.add_column("faborder", sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString()))
    op.add_column("faborder", sa.Column("invoice_date", sa.DateTime()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("faborder", "invoice_date")
    op.drop_column("faborder", "invoice_number")
    op.drop_column("faborder", "invoice_str")
    op.drop_column("faborder", "paid")
    # ### end Alembic commands ###
