"""add user_id to invoice table

Revision ID: 7c78c62190e8
Revises: 20bed580bb27
Create Date: 2025-03-02 13:36:29.602892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7c78c62190e8"
down_revision: Union[str, None] = "20bed580bb27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fabinvoice", sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fabinvoice", "user_id")
    # ### end Alembic commands ###
