"""Add Invoice HTML Column

Revision ID: 9fe6a6757807
Revises: 20ea2521dc53
Create Date: 2025-02-18 10:19:55.795863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9fe6a6757807"
down_revision: Union[str, None] = "20ea2521dc53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fabinvoice", sa.Column("invoice_html", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fabinvoice", "invoice_html")
    # ### end Alembic commands ###
