"""Create Base Tables

Revision ID: c994d4560270
Revises:
Create Date: 2025-01-24 22:13:55.505667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c994d4560270"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fabitem",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("tax_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "faborder",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "fabcartitem",
        sa.Column("fk_item", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_item"],
            ["fabitem.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "faborderitem",
        sa.Column("fk_order", sa.Integer(), nullable=False),
        sa.Column("fk_item", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_item"],
            ["fabitem.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["fk_order"],
            ["faborder.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("faborderitem")
    op.drop_table("fabcartitem")
    op.drop_table("faborder")
    op.drop_table("fabitem")
    # ### end Alembic commands ###
