name: Docker Image CI

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build FAB API Image'
            run: |
              docker build fab-api --tag ghcr.io/fabkoblenz/fab-app-api:$BRANCH_NAME
              docker push ghcr.io/fabkoblenz/fab-app-api:$BRANCH_NAME
              
          - name: 'Build FAB Frontend Image'
            run: |
              docker build fab-ui --tag ghcr.io/fabkoblenz/fab-app-ui:$BRANCH_NAME
              docker push ghcr.io/fabkoblenz/fab-app-ui:$BRANCH_NAME

